//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class User : object
    {
        
        private string userIdField;
        
        private string userPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Budget", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class Budget : object
    {
        
        private bool hasLimitField;
        
        private int idField;
        
        private float limitField;
        
        private ServiceReference1.Target[] targetsField;
        
        private ServiceReference1.Target[] targetsNField;
        
        private string targetsStringField;
        
        private string userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hasLimit
        {
            get
            {
                return this.hasLimitField;
            }
            set
            {
                this.hasLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Target[] targets
        {
            get
            {
                return this.targetsField;
            }
            set
            {
                this.targetsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Target[] targetsN
        {
            get
            {
                return this.targetsNField;
            }
            set
            {
                this.targetsNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string targetsString
        {
            get
            {
                return this.targetsStringField;
            }
            set
            {
                this.targetsStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Target", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class Target : object
    {
        
        private int budgetIdField;
        
        private float colFirstField;
        
        private float colFourthField;
        
        private float colSecondField;
        
        private float colThirdField;
        
        private float currentMoneyField;
        
        private System.DateTime deadLineField;
        
        private string deadLineTextField;
        
        private string descriptionField;
        
        private int idField;
        
        private bool isClosedField;
        
        private bool isOpenedField;
        
        private System.DateTime lastAccessTimeField;
        
        private string nameField;
        
        private float requiredMoneyField;
        
        private string totalTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int budgetId
        {
            get
            {
                return this.budgetIdField;
            }
            set
            {
                this.budgetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colFirst
        {
            get
            {
                return this.colFirstField;
            }
            set
            {
                this.colFirstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colFourth
        {
            get
            {
                return this.colFourthField;
            }
            set
            {
                this.colFourthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colSecond
        {
            get
            {
                return this.colSecondField;
            }
            set
            {
                this.colSecondField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colThird
        {
            get
            {
                return this.colThirdField;
            }
            set
            {
                this.colThirdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float currentMoney
        {
            get
            {
                return this.currentMoneyField;
            }
            set
            {
                this.currentMoneyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deadLine
        {
            get
            {
                return this.deadLineField;
            }
            set
            {
                this.deadLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deadLineText
        {
            get
            {
                return this.deadLineTextField;
            }
            set
            {
                this.deadLineTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isClosed
        {
            get
            {
                return this.isClosedField;
            }
            set
            {
                this.isClosedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isOpened
        {
            get
            {
                return this.isOpenedField;
            }
            set
            {
                this.isOpenedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime lastAccessTime
        {
            get
            {
                return this.lastAccessTimeField;
            }
            set
            {
                this.lastAccessTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float requiredMoney
        {
            get
            {
                return this.requiredMoneyField;
            }
            set
            {
                this.requiredMoneyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalText
        {
            get
            {
                return this.totalTextField;
            }
            set
            {
                this.totalTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class Category : object
    {
        
        private int idField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoodsForCheque", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class GoodsForCheque : object
    {
        
        private int amountField;
        
        private string amountTextField;
        
        private int categoryField;
        
        private int idField;
        
        private int idGFCField;
        
        private string nameField;
        
        private string nameWithPriceField;
        
        private float priceField;
        
        private string priceTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amountText
        {
            get
            {
                return this.amountTextField;
            }
            set
            {
                this.amountTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idGFC
        {
            get
            {
                return this.idGFCField;
            }
            set
            {
                this.idGFCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameWithPrice
        {
            get
            {
                return this.nameWithPriceField;
            }
            set
            {
                this.nameWithPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string priceText
        {
            get
            {
                return this.priceTextField;
            }
            set
            {
                this.priceTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cheque", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class Cheque : object
    {
        
        private ServiceReference1.GoodsForCheque[] allGoodsField;
        
        private string allGoodsStringField;
        
        private float colFirstField;
        
        private float colFourthField;
        
        private float colSecondField;
        
        private float colThirdField;
        
        private System.DateTime dateField;
        
        private string dateTextField;
        
        private ServiceReference1.GoodsForCheque[] goodsField;
        
        private ServiceReference1.GoodsForCheque[] goodsNField;
        
        private string goodsStringField;
        
        private int idField;
        
        private bool isClosedField;
        
        private bool isOpenedField;
        
        private string nameField;
        
        private float totalPriceField;
        
        private string totalPriceTextField;
        
        private string userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.GoodsForCheque[] allGoods
        {
            get
            {
                return this.allGoodsField;
            }
            set
            {
                this.allGoodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string allGoodsString
        {
            get
            {
                return this.allGoodsStringField;
            }
            set
            {
                this.allGoodsStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colFirst
        {
            get
            {
                return this.colFirstField;
            }
            set
            {
                this.colFirstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colFourth
        {
            get
            {
                return this.colFourthField;
            }
            set
            {
                this.colFourthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colSecond
        {
            get
            {
                return this.colSecondField;
            }
            set
            {
                this.colSecondField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colThird
        {
            get
            {
                return this.colThirdField;
            }
            set
            {
                this.colThirdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateText
        {
            get
            {
                return this.dateTextField;
            }
            set
            {
                this.dateTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.GoodsForCheque[] goods
        {
            get
            {
                return this.goodsField;
            }
            set
            {
                this.goodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.GoodsForCheque[] goodsN
        {
            get
            {
                return this.goodsNField;
            }
            set
            {
                this.goodsNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string goodsString
        {
            get
            {
                return this.goodsStringField;
            }
            set
            {
                this.goodsStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isClosed
        {
            get
            {
                return this.isClosedField;
            }
            set
            {
                this.isClosedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isOpened
        {
            get
            {
                return this.isOpenedField;
            }
            set
            {
                this.isOpenedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float totalPrice
        {
            get
            {
                return this.totalPriceField;
            }
            set
            {
                this.totalPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string totalPriceText
        {
            get
            {
                return this.totalPriceTextField;
            }
            set
            {
                this.totalPriceTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Good", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class Good : object
    {
        
        private ServiceReference1.Category[] allCategoriesField;
        
        private int categoryField;
        
        private float colFirstField;
        
        private float colSecondField;
        
        private float colThirdField;
        
        private int idField;
        
        private bool isClosedField;
        
        private bool isOpenedField;
        
        private string nameField;
        
        private string nameWithPriceField;
        
        private float priceField;
        
        private string priceTextField;
        
        private string selectedField;
        
        private string userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Category[] allCategories
        {
            get
            {
                return this.allCategoriesField;
            }
            set
            {
                this.allCategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colFirst
        {
            get
            {
                return this.colFirstField;
            }
            set
            {
                this.colFirstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colSecond
        {
            get
            {
                return this.colSecondField;
            }
            set
            {
                this.colSecondField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float colThird
        {
            get
            {
                return this.colThirdField;
            }
            set
            {
                this.colThirdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isClosed
        {
            get
            {
                return this.isClosedField;
            }
            set
            {
                this.isClosedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isOpened
        {
            get
            {
                return this.isOpenedField;
            }
            set
            {
                this.isOpenedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameWithPrice
        {
            get
            {
                return this.nameWithPriceField;
            }
            set
            {
                this.nameWithPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string priceText
        {
            get
            {
                return this.priceTextField;
            }
            set
            {
                this.priceTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string selected
        {
            get
            {
                return this.selectedField;
            }
            set
            {
                this.selectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recomendation", Namespace="http://schemas.datacontract.org/2004/07/WCFLibraryForTP")]
    public partial class Recomendation : object
    {
        
        private string categoryNameField;
        
        private int cathegoryIdField;
        
        private string descriptionField;
        
        private string nameField;
        
        private int recomendationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoryName
        {
            get
            {
                return this.categoryNameField;
            }
            set
            {
                this.categoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cathegoryId
        {
            get
            {
                return this.cathegoryIdField;
            }
            set
            {
                this.cathegoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int recomendationId
        {
            get
            {
                return this.recomendationIdField;
            }
            set
            {
                this.recomendationIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        string AddUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckLogin", ReplyAction="http://tempuri.org/IService1/CheckLoginResponse")]
        int CheckLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckLogin", ReplyAction="http://tempuri.org/IService1/CheckLoginResponse")]
        System.Threading.Tasks.Task<int> CheckLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignIn", ReplyAction="http://tempuri.org/IService1/SignInResponse")]
        int SignIn(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignIn", ReplyAction="http://tempuri.org/IService1/SignInResponse")]
        System.Threading.Tasks.Task<int> SignInAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserObject", ReplyAction="http://tempuri.org/IService1/AddUserObjectResponse")]
        int AddUserObject(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUserObject", ReplyAction="http://tempuri.org/IService1/AddUserObjectResponse")]
        System.Threading.Tasks.Task<int> AddUserObjectAsync(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignInObject", ReplyAction="http://tempuri.org/IService1/SignInObjectResponse")]
        int SignInObject(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SignInObject", ReplyAction="http://tempuri.org/IService1/SignInObjectResponse")]
        System.Threading.Tasks.Task<int> SignInObjectAsync(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBudget", ReplyAction="http://tempuri.org/IService1/AddBudgetResponse")]
        ServiceReference1.Budget AddBudget(float limit, bool haslimit, string userId, string targetsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBudget", ReplyAction="http://tempuri.org/IService1/AddBudgetResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Budget> AddBudgetAsync(float limit, bool haslimit, string userId, string targetsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBudget", ReplyAction="http://tempuri.org/IService1/GetBudgetResponse")]
        ServiceReference1.Budget GetBudget(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBudget", ReplyAction="http://tempuri.org/IService1/GetBudgetResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Budget> GetBudgetAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBudget", ReplyAction="http://tempuri.org/IService1/UpdateBudgetResponse")]
        ServiceReference1.Budget UpdateBudget(ServiceReference1.Budget budget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBudget", ReplyAction="http://tempuri.org/IService1/UpdateBudgetResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Budget> UpdateBudgetAsync(ServiceReference1.Budget budget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBudget", ReplyAction="http://tempuri.org/IService1/DeleteBudgetResponse")]
        string DeleteBudget(int idBudget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBudget", ReplyAction="http://tempuri.org/IService1/DeleteBudgetResponse")]
        System.Threading.Tasks.Task<string> DeleteBudgetAsync(int idBudget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        ServiceReference1.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCaterories", ReplyAction="http://tempuri.org/IService1/AddCateroriesResponse")]
        int AddCaterories(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCaterories", ReplyAction="http://tempuri.org/IService1/AddCateroriesResponse")]
        System.Threading.Tasks.Task<int> AddCateroriesAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoryName", ReplyAction="http://tempuri.org/IService1/GetCategoryNameResponse")]
        string GetCategoryName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoryName", ReplyAction="http://tempuri.org/IService1/GetCategoryNameResponse")]
        System.Threading.Tasks.Task<string> GetCategoryNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCheque", ReplyAction="http://tempuri.org/IService1/AddChequeResponse")]
        ServiceReference1.Cheque AddCheque(string name, System.DateTime date, string dateText, float totalPrice, string userId, string goodsString, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, float colFourth, string allGoodCheque, ServiceReference1.GoodsForCheque[] goods);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCheque", ReplyAction="http://tempuri.org/IService1/AddChequeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cheque> AddChequeAsync(string name, System.DateTime date, string dateText, float totalPrice, string userId, string goodsString, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, float colFourth, string allGoodCheque, ServiceReference1.GoodsForCheque[] goods);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCheque", ReplyAction="http://tempuri.org/IService1/DeleteChequeResponse")]
        string DeleteCheque(int idCheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCheque", ReplyAction="http://tempuri.org/IService1/DeleteChequeResponse")]
        System.Threading.Tasks.Task<string> DeleteChequeAsync(int idCheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCheque", ReplyAction="http://tempuri.org/IService1/GetChequeResponse")]
        ServiceReference1.Cheque GetCheque(int idCheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCheque", ReplyAction="http://tempuri.org/IService1/GetChequeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cheque> GetChequeAsync(int idCheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCheque", ReplyAction="http://tempuri.org/IService1/UpdateChequeResponse")]
        ServiceReference1.Cheque UpdateCheque(ServiceReference1.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCheque", ReplyAction="http://tempuri.org/IService1/UpdateChequeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cheque> UpdateChequeAsync(ServiceReference1.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCheque", ReplyAction="http://tempuri.org/IService1/GetAllChequeResponse")]
        ServiceReference1.Cheque[] GetAllCheque(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCheque", ReplyAction="http://tempuri.org/IService1/GetAllChequeResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cheque[]> GetAllChequeAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChequeInInterval", ReplyAction="http://tempuri.org/IService1/GetChequeInIntervalResponse")]
        ServiceReference1.Cheque[] GetChequeInInterval(string userId, System.DateTime A, System.DateTime B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChequeInInterval", ReplyAction="http://tempuri.org/IService1/GetChequeInIntervalResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cheque[]> GetChequeInIntervalAsync(string userId, System.DateTime A, System.DateTime B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGood", ReplyAction="http://tempuri.org/IService1/AddGoodResponse")]
        ServiceReference1.Good AddGood(string name, string nameWithPrice, float price, string priceText, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, int category, string userId, string selected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGood", ReplyAction="http://tempuri.org/IService1/AddGoodResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Good> AddGoodAsync(string name, string nameWithPrice, float price, string priceText, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, int category, string userId, string selected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGood", ReplyAction="http://tempuri.org/IService1/DeleteGoodResponse")]
        string DeleteGood(int idGood);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGood", ReplyAction="http://tempuri.org/IService1/DeleteGoodResponse")]
        System.Threading.Tasks.Task<string> DeleteGoodAsync(int idGood);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGood", ReplyAction="http://tempuri.org/IService1/GetGoodResponse")]
        ServiceReference1.Good GetGood(int idGood);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGood", ReplyAction="http://tempuri.org/IService1/GetGoodResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Good> GetGoodAsync(int idGood);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGood", ReplyAction="http://tempuri.org/IService1/UpdateGoodResponse")]
        ServiceReference1.Good UpdateGood(ServiceReference1.Good good);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGood", ReplyAction="http://tempuri.org/IService1/UpdateGoodResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Good> UpdateGoodAsync(ServiceReference1.Good good);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGoods", ReplyAction="http://tempuri.org/IService1/GetAllGoodsResponse")]
        ServiceReference1.Good[] GetAllGoods(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGoods", ReplyAction="http://tempuri.org/IService1/GetAllGoodsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Good[]> GetAllGoodsAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecomendationCath", ReplyAction="http://tempuri.org/IService1/GetRecomendationCathResponse")]
        ServiceReference1.Recomendation[] GetRecomendationCath(int idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecomendationCath", ReplyAction="http://tempuri.org/IService1/GetRecomendationCathResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Recomendation[]> GetRecomendationCathAsync(int idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRecomendations", ReplyAction="http://tempuri.org/IService1/GetAllRecomendationsResponse")]
        ServiceReference1.Recomendation[] GetAllRecomendations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRecomendations", ReplyAction="http://tempuri.org/IService1/GetAllRecomendationsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Recomendation[]> GetAllRecomendationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecomendationCathRandom", ReplyAction="http://tempuri.org/IService1/GetRecomendationCathRandomResponse")]
        ServiceReference1.Recomendation GetRecomendationCathRandom(int idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecomendationCathRandom", ReplyAction="http://tempuri.org/IService1/GetRecomendationCathRandomResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Recomendation> GetRecomendationCathRandomAsync(int idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddRecomendation", ReplyAction="http://tempuri.org/IService1/AddRecomendationResponse")]
        int AddRecomendation(ServiceReference1.Recomendation recomendation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddRecomendation", ReplyAction="http://tempuri.org/IService1/AddRecomendationResponse")]
        System.Threading.Tasks.Task<int> AddRecomendationAsync(ServiceReference1.Recomendation recomendation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string AddUser(string login, string password)
        {
            return base.Channel.AddUser(login, password);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(string login, string password)
        {
            return base.Channel.AddUserAsync(login, password);
        }
        
        public int CheckLogin(string login)
        {
            return base.Channel.CheckLogin(login);
        }
        
        public System.Threading.Tasks.Task<int> CheckLoginAsync(string login)
        {
            return base.Channel.CheckLoginAsync(login);
        }
        
        public int SignIn(string login, string password)
        {
            return base.Channel.SignIn(login, password);
        }
        
        public System.Threading.Tasks.Task<int> SignInAsync(string login, string password)
        {
            return base.Channel.SignInAsync(login, password);
        }
        
        public int AddUserObject(ServiceReference1.User user)
        {
            return base.Channel.AddUserObject(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserObjectAsync(ServiceReference1.User user)
        {
            return base.Channel.AddUserObjectAsync(user);
        }
        
        public int SignInObject(ServiceReference1.User user)
        {
            return base.Channel.SignInObject(user);
        }
        
        public System.Threading.Tasks.Task<int> SignInObjectAsync(ServiceReference1.User user)
        {
            return base.Channel.SignInObjectAsync(user);
        }
        
        public ServiceReference1.Budget AddBudget(float limit, bool haslimit, string userId, string targetsString)
        {
            return base.Channel.AddBudget(limit, haslimit, userId, targetsString);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Budget> AddBudgetAsync(float limit, bool haslimit, string userId, string targetsString)
        {
            return base.Channel.AddBudgetAsync(limit, haslimit, userId, targetsString);
        }
        
        public ServiceReference1.Budget GetBudget(string userId)
        {
            return base.Channel.GetBudget(userId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Budget> GetBudgetAsync(string userId)
        {
            return base.Channel.GetBudgetAsync(userId);
        }
        
        public ServiceReference1.Budget UpdateBudget(ServiceReference1.Budget budget)
        {
            return base.Channel.UpdateBudget(budget);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Budget> UpdateBudgetAsync(ServiceReference1.Budget budget)
        {
            return base.Channel.UpdateBudgetAsync(budget);
        }
        
        public string DeleteBudget(int idBudget)
        {
            return base.Channel.DeleteBudget(idBudget);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBudgetAsync(int idBudget)
        {
            return base.Channel.DeleteBudgetAsync(idBudget);
        }
        
        public ServiceReference1.Category[] GetCategories()
        {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Category[]> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        public int AddCaterories(string name)
        {
            return base.Channel.AddCaterories(name);
        }
        
        public System.Threading.Tasks.Task<int> AddCateroriesAsync(string name)
        {
            return base.Channel.AddCateroriesAsync(name);
        }
        
        public string GetCategoryName(int id)
        {
            return base.Channel.GetCategoryName(id);
        }
        
        public System.Threading.Tasks.Task<string> GetCategoryNameAsync(int id)
        {
            return base.Channel.GetCategoryNameAsync(id);
        }
        
        public ServiceReference1.Cheque AddCheque(string name, System.DateTime date, string dateText, float totalPrice, string userId, string goodsString, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, float colFourth, string allGoodCheque, ServiceReference1.GoodsForCheque[] goods)
        {
            return base.Channel.AddCheque(name, date, dateText, totalPrice, userId, goodsString, isOpened, isClosed, colFirst, colSecond, colThird, colFourth, allGoodCheque, goods);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cheque> AddChequeAsync(string name, System.DateTime date, string dateText, float totalPrice, string userId, string goodsString, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, float colFourth, string allGoodCheque, ServiceReference1.GoodsForCheque[] goods)
        {
            return base.Channel.AddChequeAsync(name, date, dateText, totalPrice, userId, goodsString, isOpened, isClosed, colFirst, colSecond, colThird, colFourth, allGoodCheque, goods);
        }
        
        public string DeleteCheque(int idCheque)
        {
            return base.Channel.DeleteCheque(idCheque);
        }
        
        public System.Threading.Tasks.Task<string> DeleteChequeAsync(int idCheque)
        {
            return base.Channel.DeleteChequeAsync(idCheque);
        }
        
        public ServiceReference1.Cheque GetCheque(int idCheque)
        {
            return base.Channel.GetCheque(idCheque);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cheque> GetChequeAsync(int idCheque)
        {
            return base.Channel.GetChequeAsync(idCheque);
        }
        
        public ServiceReference1.Cheque UpdateCheque(ServiceReference1.Cheque cheque)
        {
            return base.Channel.UpdateCheque(cheque);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cheque> UpdateChequeAsync(ServiceReference1.Cheque cheque)
        {
            return base.Channel.UpdateChequeAsync(cheque);
        }
        
        public ServiceReference1.Cheque[] GetAllCheque(string userId)
        {
            return base.Channel.GetAllCheque(userId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cheque[]> GetAllChequeAsync(string userId)
        {
            return base.Channel.GetAllChequeAsync(userId);
        }
        
        public ServiceReference1.Cheque[] GetChequeInInterval(string userId, System.DateTime A, System.DateTime B)
        {
            return base.Channel.GetChequeInInterval(userId, A, B);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cheque[]> GetChequeInIntervalAsync(string userId, System.DateTime A, System.DateTime B)
        {
            return base.Channel.GetChequeInIntervalAsync(userId, A, B);
        }
        
        public ServiceReference1.Good AddGood(string name, string nameWithPrice, float price, string priceText, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, int category, string userId, string selected)
        {
            return base.Channel.AddGood(name, nameWithPrice, price, priceText, isOpened, isClosed, colFirst, colSecond, colThird, category, userId, selected);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Good> AddGoodAsync(string name, string nameWithPrice, float price, string priceText, bool isOpened, bool isClosed, float colFirst, float colSecond, float colThird, int category, string userId, string selected)
        {
            return base.Channel.AddGoodAsync(name, nameWithPrice, price, priceText, isOpened, isClosed, colFirst, colSecond, colThird, category, userId, selected);
        }
        
        public string DeleteGood(int idGood)
        {
            return base.Channel.DeleteGood(idGood);
        }
        
        public System.Threading.Tasks.Task<string> DeleteGoodAsync(int idGood)
        {
            return base.Channel.DeleteGoodAsync(idGood);
        }
        
        public ServiceReference1.Good GetGood(int idGood)
        {
            return base.Channel.GetGood(idGood);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Good> GetGoodAsync(int idGood)
        {
            return base.Channel.GetGoodAsync(idGood);
        }
        
        public ServiceReference1.Good UpdateGood(ServiceReference1.Good good)
        {
            return base.Channel.UpdateGood(good);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Good> UpdateGoodAsync(ServiceReference1.Good good)
        {
            return base.Channel.UpdateGoodAsync(good);
        }
        
        public ServiceReference1.Good[] GetAllGoods(string userId)
        {
            return base.Channel.GetAllGoods(userId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Good[]> GetAllGoodsAsync(string userId)
        {
            return base.Channel.GetAllGoodsAsync(userId);
        }
        
        public ServiceReference1.Recomendation[] GetRecomendationCath(int idCategory)
        {
            return base.Channel.GetRecomendationCath(idCategory);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Recomendation[]> GetRecomendationCathAsync(int idCategory)
        {
            return base.Channel.GetRecomendationCathAsync(idCategory);
        }
        
        public ServiceReference1.Recomendation[] GetAllRecomendations()
        {
            return base.Channel.GetAllRecomendations();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Recomendation[]> GetAllRecomendationsAsync()
        {
            return base.Channel.GetAllRecomendationsAsync();
        }
        
        public ServiceReference1.Recomendation GetRecomendationCathRandom(int idCategory)
        {
            return base.Channel.GetRecomendationCathRandom(idCategory);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Recomendation> GetRecomendationCathRandomAsync(int idCategory)
        {
            return base.Channel.GetRecomendationCathRandomAsync(idCategory);
        }
        
        public int AddRecomendation(ServiceReference1.Recomendation recomendation)
        {
            return base.Channel.AddRecomendation(recomendation);
        }
        
        public System.Threading.Tasks.Task<int> AddRecomendationAsync(ServiceReference1.Recomendation recomendation)
        {
            return base.Channel.AddRecomendationAsync(recomendation);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.100.6:8733/Design_Time_Addresses/WCFLibraryForTP/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
